export const UPDATE_ONBOARDING_STATUS = 'UPDATE_ONBOARDING_STATUS';
export const UPDATE_USER_AUTH_DETAILS = 'UPDATE_USER_AUTH_DETAILS';
export const UPDATE_USER_LOGIN = 'UPDATE_USER_LOGIN';
export const UPDATE_LOGGED_IN_STATUS = 'UPDATE_LOGGED_IN_STATUS';
export const UPDATE_USER_ACCESS_TOKEN = 'UPDATE_USER_ACCESS_TOKEN';
export const LOGOUT_USER = 'LOGOUT_USER';

// NEW
export const UPDATE_SEARCH_FILTER = 'UPDATE_SEARCH_FILTER';
export const ADD_SEARCH_FILTER = 'ADD_SEARCH_FILTER';
export const REMOVE_SEARCH_FILTER = 'REMOVE_SEARCH_FILTER';
export const UPDATE_RADIO_SELECTION = 'UPDATE_RADIO_SELECTION';
