export const UPDATE_ONBOARDING_STATUS = 'UPDATE_ONBOARDING_STATUS';
export const UPDATE_USER_LOGIN = 'UPDATE_USER_LOGIN';
export const UPDATE_LOGGED_IN_STATUS = 'UPDATE_LOGGED_IN_STATUS';
export const UPDATE_USER_ACCESS_TOKEN = 'UPDATE_USER_ACCESS_TOKEN';
export const UPDATE_USER_REFRESH_TOKEN = 'UPDATE_USER_REFRESH_TOKEN';
export const UPDATE_POST_DETAILS = 'UPDATE_POST_DETAILS';
export const UPDATE_FEATURED_POST = 'UPDATE_FEATURED_POST';
export const CLEAR_NEWS = 'CLEAR_NEWS';
export const LOGOUT_USER = 'LOGOUT_USER';
export const UPDATE_USER_BIO = "UPDATE_USER_BIO";
export const UPDATE_USER_LEVEL_BIO_GENDER = "UPDATE_USER_LEVEL_BIO_GENDER";
export const UPDATE_USER_PROFILE = "UPDATE_USER_PROFILE";
export const UPDATE_GREETING = "UPDATE_GREETING";


// QUIZ
export const UPDATE_POPULAR_SEARCH = "UPDATE_POPULAR_SEARCH";
export const UPDATE_TEST = "UPDATE_TEST";
