export const UPDATE_SEARCH_FILTER = 'UPDATE_SEARCH_FILTER';
export const ADD_SEARCH_FILTER = 'ADD_SEARCH_FILTER';
export const REMOVE_SEARCH_FILTER = 'REMOVE_SEARCH_FILTER';

// POSTING PRODUCTS
export const POST_PRODUCT = 'POST_PRODUCT';
